version: "3.9"

services:
  # Use a local nginx config and drop TLS
  proxy:
    volumes:
      - ./reverse-proxy/nginx.local.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"     # only HTTP for local
    # remove the cert mounts locally

  # Make sure PostgREST allows localhost and points to the local proxy URL
  supabase-rest:
    environment:
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost/rest
      PGRST_CORS_ALLOWED_ORIGINS: http://localhost

  # Make sure GoTrue knows local external URLs (used in redirects and CORS)
  supabase-auth:
    environment:
      API_EXTERNAL_URL: http://localhost/auth
      GOTRUE_SITE_URL: http://localhost

  # (Optional) expose backend directly for debugging without the proxy:
  # backend:
  #   ports:
  #     - "3001:3001"

  # (Optional) if you want to expose frontend directly (skip proxy while dev):
  frontend:
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    environment:
      # if your dev server needs it
      NODE_ENV: development
